import type { Metadata } from 'next'
import { Geist } from 'next/font/google'

import './globals.css'

import BackgroundWorker from '@/components/background-sync'
import { Navbar } from '@/components/navbar'
import Providers from '@/components/providers'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Keeper',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} antialiased`}>
        <Providers>
          <Navbar />
          {children}
          <BackgroundWorker />
        </Providers>
      </body>
    </html>
  )
}
